name: Docker Build and Test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker images
      run: docker compose build

    - name: Run Test Suite
      run: |
        docker compose up -d
        # Give services time to stabilize
        sleep 15
        # Sync DB schema
        docker compose exec -T backend npx prisma db push --skip-generate
        # Run actual tests
        docker compose exec -T backend npx jest tests/api.test.js

        docker compose down

